server:
    port: ${myserverport:8087}
spring:
  application:
    name: cinema-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false
  datasource:
    url: jdbc:oracle:thin:@192.168.182.122:1521/ORCLCDB.localdomain
    driver-class-name: oracle.jdbc.OracleDriver
    username: dummy
    password: dummy
mybatis:
  type-aliases-package: rs.ac.bg.fon.cinema
  configuration:
    jdbc-type-for-null: 'NULL'
cinema:
  worktime:
    opens: 11
    closes: '23'
---
 
spring:
  profiles: development-w
  datasource:
    url: jdbc:oracle:thin:@192.168.182.122:1521/ORCLCDB.localdomain
    driver-class-name: oracle.jdbc.OracleDriver
    username: dummy
    password: dummy
  logging: 
    level: 
      rs.ac.bg.fon.cinema.mapper: TRACE
      org.mybatis: TRACE
      org.springframework.boot.autoconfigure.jdbc: TRACE
      org.springframework.jdbc: TRACE

---
 
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  logging: 
    level: 
      rs.ac.bg.fon.cinema.mapper: TRACE
      org.mybatis: TRACE
      org.springframework.boot.autoconfigure.jdbc: TRACE
      org.springframework.jdbc: TRACE