insert into genres(id, name) values((select sq_genres.nextval from dual), 'Absurdist');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Action');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Adventure');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Comedy');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Crime');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Drama');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Fantasy');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Historical');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Historical fiction');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Magical realism');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Mystery');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Paranoid fiction');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Philosophical');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Political');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Romance');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Saga');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Satire');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Science fiction');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Social');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Speculative');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Thriller');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Urban');
insert into genres(id, name) values((select sq_genres.nextval from dual), 'Western');

insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Universal Pictures');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Warner Bros');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Sony Pictures Motion Picture Group');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Walt Disney Studios');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), '20th Century Fox');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Paramount Pictures');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Lionsgate Films');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'The Weinstein Company');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'Metro-Goldwyn-Mayer Studios');
insert into production_companies(id, name) values((select sq_production_companies.nextval from dual), 'DreamWorks Pictures');
